### ISSUE TITLE
Neat tutorial, but there are more than a few grammar/spelling mistakes.

### ISSUE THREAD

**Issue by quadrupleslap** [tomaka/vulkano-www#6]
[For example](https://github.com/tomaka/vulkano-www/blob/2b5f9cd5ebc1ce12d7ec68ca0a12eb4662b28207/content/guide-image-export.md)

> This might **you look stupid**, but think about the fact that it's the GPU that wrote the content of the image. In the next sections we will do more than just fill an image with blue, but we will continue to retreive the image's content and write it to a PNG file.

Also, isn't that what you did in *this* section?

**Comment by tomaka** [comment]
Oh, that's embarrassing. Thanks for the report.
